### ISSUE TITLE
Quantumult x商店版更新了导致脚本错误

### ISSUE THREAD

**Issue by Kisoul** [eHpo1/Rules#10]
![8FB34281-DB22-4AFB-8AB9-1A919D0311BF](https://user-images.githubusercontent.com/32985553/77865149-6fb7d680-725f-11ea-96f5-dd8e63b6fb40.png)
商店版更新到1.0.6build212了，出现错误

**Comment by eHpo1** [comment]
> ![8FB34281-DB22-4AFB-8AB9-1A919D0311BF](https://user-images.githubusercontent.com/32985553/77865149-6fb7d680-725f-11ea-96f5-dd8e63b6fb40.png)
> 商店版更新到1.0.6build212了，出现错误
> 

这很明显不是我规则的问题吧。
