### ISSUE TITLE
建议: 从 Liby.list 中移除 amdc.m.taobao.com

### ISSUE THREAD

**Issue by hly0928** [eHpo1/Rules#11]
某些淘宝比价脚本（比如 [这个](https://github.com/yichahucha/surge/tree/master)）需要对该域名相关返回体进行修改，Reject 后会导致脚本失效。

**Comment by eHpo1** [comment]
> 某些淘宝比价脚本（比如 [这个](https://github.com/yichahucha/surge/tree/master)）需要对该域名相关返回体进行修改，Reject 后会导致脚本失效。

不会失效，相反拦截这个会让比价更稳固。

**Comment by hly0928** [comment]
> 不会失效，相反拦截这个会让比价更稳固。

重装后正常，抱歉打扰了 :)
