### ISSUE TITLE
建议: 分离 Region.list

### ISSUE THREAD

**Issue by hly0928** [eHpo1/Rules#12]
一般来说，`LAN` 和 `GeoIP,CN` 并不一定走相同的策略（前者直连，后者不一定）。

另外，`DOMAIN,captive.apple.com` 这条规则应该是无效的，会被 `Apple_API.list` 中的 `DOMAIN-SUFFIX,apple.com` 提前命中。

**Comment by eHpo1** [comment]
> 一般来说，`LAN` 和 `GeoIP,CN` 并不一定走相同的策略（前者直连，后者不一定）。
> 
> 另外，`DOMAIN,captive.apple.com` 这条规则应该是无效的，会被 `Apple_API.list` 中的 `DOMAIN-SUFFIX,apple.com` 提前命中。


captive.apple.com的确考虑不周，不过这个链接似乎是公司内网使用，lan与geoip,cn绑定是因为region原本是设定为以后修正规则使用，设想是单独一份修正规则列表可能会有用户忽略，以后可能考虑分离出geoip

**Comment by hly0928** [comment]
👌，我感觉目前热门的规则 Repo 大部分还是把 GeoIP 写在本地 conf 里的 🌚
