### ISSUE TITLE
一些其他的建议

### ISSUE THREAD

**Issue by hly0928** [eHpo1/Rules#13]
首先感谢作者，感觉目前此 repo 的规则最能满足个人需要 :D

还有一些其他的建议就在此一并提出：

1. `Sub/` 下可以添加一个 `Netease Music.list`，可参考 [UnblockNeteaseMusic 项目](https://github.com/nondanee/UnblockNeteaseMusic/blob/master/src/hook.js#L25) 或者 lhie1 大佬的现成 [list](https://github.com/lhie1/Rules/blob/master/Surge/Surge%203/Provider/Media/Netease%20Music.list)

2. 示例配置的 `[Rule]` 部分有一些小问题，比如 `Global.list` 和 `FINAL` 走同一个策略的话，相当于无法控制黑/白名单模式；还有 `[Proxy Group]` 里 `Global` 跟 `Domestic` 相互嵌套的问题，虽然是示例但容易误导小白 🌚

3. 可否考虑把 Surge MitM hostname 单独出一个文件，方便 Surgio 等软件订阅？

3. Quantumult X 可以添加 [Qure 图标组](https://github.com/Koolson/Qure) 美化：
```
static=Global, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Global.png
static=Domestic, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Domestic.png
static=AdBlock, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Advertising.png
static=Apple_API, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Apple.png
static=Apple_CDN, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/App_Store.png
static=AsianMedia, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/DomesticMedia.png
static=GlobalMedia, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/GlobalMedia.png
```

**Comment by eHpo1** [comment]
> 首先感谢作者，感觉目前此 repo 的规则最能满足个人需要 :D
> 
> 还有一些其他的建议就在此一并提出：
> 
> 1. `Sub/` 下可以添加一个 `Netease Music.list`，可参考 [UnblockNeteaseMusic 项目](https://github.com/nondanee/UnblockNeteaseMusic/blob/master/src/hook.js#L25) 或者 lhie1 大佬的现成 [list](https://github.com/lhie1/Rules/blob/master/Surge/Surge%203/Provider/Media/Netease%20Music.list)
> 
> 2. 示例配置的 `[Rule]` 部分有一些小问题，比如 `Global.list` 和 `FINAL` 走同一个策略的话，相当于无法控制黑/白名单模式；还有 `[Proxy Group]` 里 `Global` 跟 `Domestic` 相互嵌套的问题，虽然是示例但容易误导小白 🌚
> 
> 3. 可否考虑把 Surge MitM hostname 单独出一个文件，方便 Surgio 等软件订阅？
> 
> 3. Quantumult X 可以添加 [Qure 图标组](https://github.com/Koolson/Qure) 美化：
> ```
> static=Global, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Global.png
> static=Domestic, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Domestic.png
> static=AdBlock, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Advertising.png
> static=Apple_API, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Apple.png
> static=Apple_CDN, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/App_Store.png
> static=AsianMedia, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/DomesticMedia.png
> static=GlobalMedia, ..., img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/GlobalMedia.png
> ```

1. 我把网易云作为回国规则问题看待，因为环境不同，不敢冒然适配回国规则，目前设想是把网易云、qq之类分到AsianMedia中，完成回国规则适配可能会需要一些时间。
2. final与global绑定也是因为回国规则，项目不会做黑白名单模式，因为很很明显白名单才是最优体验。嵌套是为了方便debug，策略组的首选项已经是排好的，只要不乱改是不会出问题。
3. hostname会单独列出来，而且考虑到手机surge用户还准备弄个捷径只更新hostname与rewrite。
4. Quantumult X的图标问题，此前也有用户提到过，目前已经与Qure作者谈妥，同意项目直接引用，在最后敲定阶段了。
5. 昨晚的captive.apple.com，纠正一下，这是一个用于连接wifi时测试有无网络的链接，准备删除相关条目。
6. 感谢您对项目的大力支持。
