### ISSUE TITLE
Liby.list中部分条目影响阿里系app的使用

### ISSUE THREAD

**Issue by Scorpion4286** [eHpo1/Rules#14]
运行环境：
服务端OpenWrt 19.07.2  ；clash v0.19.0
客户端iOS & MIUI

问题规则：
  - IP-CIDR,203.119.206.64/32,AdBlock,no-resolve
  - IP-CIDR,203.119.211.219/32,AdBlock,no-resolve

现象：
部分阿里系app显示无法连接网络，并且无法加载任何信息。eg. 阿里通信、飞猪旅行
clash log中显示客户端在反复请求上述两个条目中的地址。
删除上述规则后app可以正常使用*。

*阿里通信仍显示未联网，但不影响使用。

**Comment by eHpo1** [comment]
> 运行环境：
> 服务端OpenWrt 19.07.2 ；clash v0.19.0
> 客户端iOS & MIUI
> 
> 问题规则：
> 
> * IP-CIDR,203.119.206.64/32,AdBlock,no-resolve
> * IP-CIDR,203.119.211.219/32,AdBlock,no-resolve
> 
> 现象：
> 部分阿里系app显示无法连接网络，并且无法加载任何信息。eg. 阿里通信、飞猪旅行
> clash log中显示客户端在反复请求上述两个条目中的地址。
> 删除上述规则后app可以正常使用*。
> 
> *阿里通信仍显示未联网，但不影响使用。

抱歉，我这边暂时没有openclash环境，等会会删除这两条。不过在其他端上使用是没有您所说的这个问题的。

**Comment by eHpo1** [comment]
已推送更新

**Comment by Scorpion4286** [comment]
收到，大佬辛苦~
