### ISSUE TITLE
和淘宝历史价格JS冲突

### ISSUE THREAD

**Issue by scyrte** [eHpo1/Rules#15]
liby.txt下的HOST, AMDC.M.TAOBAO.COM, ADBLOCK这条规则，匹配http://amdc.m.taobao.com/amdc/mobileDispatch这个地址，和^https?://amdc\.m\.taobao\.com/amdc/mobileDispatch url script-response-body yichahucha/tb_price.js冲突，导致一淘异常。

**Comment by eHpo1** [comment]
> liby.txt下的HOST, AMDC.M.TAOBAO.COM, ADBLOCK这条规则，匹配http://amdc.m.taobao.com/amdc/mobileDispatch这个地址，和^https?://amdc\.m\.taobao\.com/amdc/mobileDispatch url script-response-body yichahucha/tb_price.js冲突，导致一淘异常。

的确会导致异常，不过与脚本没有关系。

**Comment by scyrte** [comment]
是否应该删除HOST, AMDC.M.TAOBAO.COM, ADBLOCK这条规则？

**Comment by eHpo1** [comment]
> 是否应该删除HOST, AMDC.M.TAOBAO.COM, ADBLOCK这条规则？

感谢反馈，明天会删除

**Comment by scyrte** [comment]
感谢。

**Comment by eHpo1** [comment]
> 感谢。

已删除相关规则。

**Comment by scyrte** [comment]
已同步，但一淘购物车里依然无法点击里面的商品链接。

**Comment by eHpo1** [comment]
> 已同步，但一淘购物车里依然无法点击里面的商品链接。

感谢再次反馈，经查实一淘无反应问题与这条规则无关，下次更新会恢复这条规则的拦截。是另一条阿里妈妈的规则^https?+:\/\/acs\.m\.taobao\.com\/gw\/mtop\.alimama\.etao\.config\.query导致的问题，下次更新将取消这条规则的拦截，一淘将采用脚本方式去除广告，阿里妈妈（淘宝联盟）可能会出现屏蔽失效的情况，注意观察。

**Comment by eHpo1** [comment]
> > 已同步，但一淘购物车里依然无法点击里面的商品链接。
> 
> 感谢再次反馈，经查实一淘无反应问题与这条规则无关，下次更新会恢复这条规则的拦截。是另一条阿里妈妈的规则^https?+:\/\/acs\.m\.taobao\.com\/gw\/mtop\.alimama\.etao\.config\.query导致的问题，下次更新将取消这条规则的拦截，一淘将采用脚本方式去除广告，阿里妈妈（淘宝联盟）可能会出现屏蔽失效的情况，注意观察。

已更新

**Comment by scyrte** [comment]
果然来广告了，忍不了，所以，做了一个测试：

[filter_local]
host-suffix, amdc.m.taobao.com, reject

这样不会导致一淘异常，是不是规则次序的问题？

**Comment by eHpo1** [comment]
> 果然来广告了，忍不了，所以，做了一个测试：
> 
> [filter_local]
> host-suffix, amdc.m.taobao.com, reject
> 
> 这样不会导致一淘异常，是不是规则次序的问题？

最新内容已经恢复了这条的屏蔽，用脚本解决了一淘广告
