### ISSUE TITLE
百度地图去广告重写需要完善

### ISSUE THREAD

**Issue by NALOTERS** [eHpo1/Rules#16]
百度地图去广告重写 ^https?+:\/\/ss0\.bdstatic\.com/.+?_\d{3}_\d{4}\.jpg会造成应用内的小图标显示不正常，需要完善

**Comment by eHpo1** [comment]
> 百度地图去广告重写 ^https?+:\/\/ss0\.bdstatic\.com/.+?_\d{3}_\d{4}\.jpg会造成应用内的小图标显示不正常，需要完善

感谢反馈，能否详细说一下是用的什么工具，哪部分小图标显示不出。

**Comment by NALOTERS** [comment]
使用软件：Surge4 tf 4.2（1546）
- 具体为百度个人中心的“离线地图”“收藏”“常用地址”等工具栏位置不能正常显示小图标

**Comment by eHpo1** [comment]
> 使用软件：Surge4 tf 4.2（1546）
> - 具体为百度个人中心的“离线地图”“收藏”“常用地址”等工具栏位置不能正常显示小图标

我这边能正常显示小图标，而且没有命中这条正则的链接。可以尝试换个网络环境看能不能加载出小图标来。

**Comment by NALOTERS** [comment]
好的，我再继续测试看看，谢谢回复

**Comment by NALOTERS** [comment]
经更换网络实测，目前已正常，issue关闭，谢谢作者！
