### ISSUE TITLE
Netflix跳区

### ISSUE THREAD

**Issue by Scorpion4286** [eHpo1/Rules#17]
运行环境：
服务端openwrt+luci-app-clash 客户端iOS+Netflix App

现象：
偶见打开Netflix App显示无网络，之后会跳至美区（我的final策略）
（Netflix 策略组中设置为新加坡）

分析：
发现启动Netflix App会直接访问几个美国IP，反推域名为prod.cloud.geo.netflix.com
推测为进行地区验证使用

建议：
将上述域名的对应ip添加至Netflix.list

**Comment by Scorpion4286** [comment]
想了下，这应该不能算bug……应该是只有clash重启等行为丢失域名与ip对应关系时才会遇到……算是个特殊情况吧……

先close了……

**Comment by eHpo1** [comment]
> 想了下，这应该不能算bug……应该是只有clash重启等行为丢失域名与ip对应关系时才会遇到……算是个特殊情况吧……
> 
> 先close了……

刚查询到这个域名dns解析是到amazon公司的ip，是可能造成错误，有没有那些出问题ip更详细的数据，比如user-agent什么的。

**Comment by Scorpion4286** [comment]
> > 想了下，这应该不能算bug……应该是只有clash重启等行为丢失域名与ip对应关系时才会遇到……算是个特殊情况吧……
> > 先close了……
> 
> 刚查询到这个域名dns解析是到amazon公司的ip，是可能造成错误，有没有那些出问题ip更详细的数据，比如user-agent什么的。

技术不精，还请海涵。
刚才尝试了下，今天的域名变成了ios.prod.ftl.netflix.com
抓包没见有用的信息，TCP握手之后跑的都是http-over-tls，啥都看不到。

**Comment by eHpo1** [comment]
> > > 想了下，这应该不能算bug……应该是只有clash重启等行为丢失域名与ip对应关系时才会遇到……算是个特殊情况吧……
> > > 先close了……
> > 
> > 刚查询到这个域名dns解析是到amazon公司的ip，是可能造成错误，有没有那些出问题ip更详细的数据，比如user-agent什么的。
> 
> 技术不精，还请海涵。
> 刚才尝试了下，今天的域名变成了ios.prod.ftl.netflix.com
> 抓包没见有用的信息，TCP握手之后跑的都是http-over-tls，啥都看不到。

该抱歉的应该是我，目前所有的路由器环境都还未测试过，所以有些问题暂时无法解决。

**Comment by eHpo1** [comment]
您好，我们查询到这两个netflix的地址使用国内dns的话会被解析到同为AS16509的
```
34.210.42.111(美国俄勒冈州波特兰 amazon.com)
54.148.37.5(美国俄勒冈州波特兰 amazon.com)
52.89.124.203(美国俄勒冈州波特兰 amazon.com)
```
可以尝试更换dns为
```
8.8.8.8
1.1.1.1
208.67.222.222
1.2.4.8
```
如果问题还未解决我们可以提供一个AS16509的所有ip的list

**Comment by Scorpion4286** [comment]
DNS我这里用的是cloudflare和Google的DoH
因为要折腾，会经常重启clash，所以这个issue应该是本地DNS缓存的原因比较大。
上面的三个ip我设置了自定义规则，这几天用下来没再出现问题。先close了。
