### ISSUE TITLE
腾讯视频去开屏广告失效

### ISSUE THREAD

**Issue by NALOTERS** [eHpo1/Rules#18]
代理工具：surge tf版4.2.0（1550）
系统版本：iOS13.4
软件版本：腾讯视频版本8.1.3
腾讯视频去开屏广告失效

# >> 腾讯视频
URL-REGEX,"^https?+:\/\/vv\.video\.qq\.com\/getvmind\?"
URL-REGEX,"^https?+:\/\/(?:(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.){3}(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\/.+?\.tc\.qq\.com\/.+?p201\.1\.mp4\?"

**Comment by eHpo1** [comment]
> 代理工具：surge tf版4.2.0（1550）
> 系统版本：iOS13.4
> 软件版本：腾讯视频版本8.1.3
> 腾讯视频去开屏广告失效
> 
> # >> 腾讯视频
> URL-REGEX,"^https?+:\/\/vv\.video\.qq\.com\/getvmind\?"
> URL-REGEX,"^https?+:\/\/(?:(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.){3}(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\/.+?\.tc\.qq\.com\/.+?p201\.1\.mp4\?"

surge环境下是有这情况，目前正在跟进。

IP-CIDR,111.30.159.168/32,REJECT,no-resolve
IP-CIDR,111.30.176.111/32,REJECT,no-resolve
