### ISSUE TITLE
淘宝打不开

### ISSUE THREAD

**Issue by h605290713** [eHpo1/Rules#19]
淘宝打不开 没有host？

**Comment by eHpo1** [comment]
> 淘宝打不开 没有host？
> 

您好，能否详细说一下使用环境。淘宝在我们这边测试能正常打开

**Comment by h605290713** [comment]
> > 淘宝打不开 没有host？
> 
> 您好，能否详细说一下使用环境。淘宝在我们这边测试能正常打开
我刚没有描述清楚 第一个是淘宝能打开 商品图片看不到 第二个是对jd的历史价格js有冲突 ，看不到了

**Comment by h605290713** [comment]
> > 淘宝打不开 没有host？
> 
> 您好，能否详细说一下使用环境。淘宝在我们这边测试能正常打开

我重新加载了一下淘宝OK了 jd历史价格脚本不行了

**Comment by eHpo1** [comment]
> > > 淘宝打不开 没有host？
> > 
> > 您好，能否详细说一下使用环境。淘宝在我们这边测试能正常打开
> 
> 我重新加载了一下淘宝OK了 jd历史价格脚本不行了

抱歉，京东查价不在规则范围内。

**Comment by h605290713** [comment]
URL-REGEX,"^https?+:\/\/api\.m\.jd\.com\/client\.action\?functionId=start$" 
这条规则删除就可以使用了

**Comment by eHpo1** [comment]
> URL-REGEX,"^https?+:\/\/api\.m\.jd\.com\/client\.action\?functionId=start$" 
> 这条规则删除就可以使用了 

这条是开屏广告。

**Comment by h605290713** [comment]
> > URL-REGEX,"^https?+://api.m.jd.com/client.action?functionId=start$"
> > 这条规则删除就可以使用了
> 
> 这条是开屏广告。

那就莫得办法

**Comment by h605290713** [comment]
> > URL-REGEX,"^https?+://api.m.jd.com/client.action?functionId=start$"
> > 这条规则删除就可以使用了
> 
> 这条是开屏广告。

我没这条规则 启动时也没广告...
