### ISSUE TITLE
全民k歌开屏广告

### ISSUE THREAD

**Issue by PatrickChuh** [eHpo1/Rules#20]
1586288701.339502270.sngdia.imtmp.net
查了dns解析记录，应该是这个域名，设置domain reject后不再有广告，前缀可能是身份识别？请添加规则

**Comment by eHpo1** [comment]
> 1586288701.339502270.sngdia.imtmp.net
> 查了dns解析记录，应该是这个域名，设置domain reject后不再有广告，前缀可能是身份识别？请添加规则

感谢反馈，全民k歌需要靠正则
^https?+:\/\/y\.gtimg\.cn\/music\/common\/\/upload\/kg_ad\/.+?\d{3,4}+x\d{4}
