### ISSUE TITLE
求去除 快递100收件 55海淘 开屏广告

### ISSUE THREAD

**Issue by a3946** [eHpo1/Rules#22]

**Comment by eHpo1** [comment]
感谢反馈，请测试
解析
```
appv6.55haitao.com
```
重写
```

# 快递100
^https?+:\/\/p\.kuaidi100\.com\/mobile\/mobileapi\.do url reject-200
# 55海淘
^https?+:\/\/appv6\.55haitao\.com\/IflyAd\/getAd url reject-200
```

**Comment by a3946** [comment]
请问是快递100还是快递100收件端的啊大佬

**Comment by eHpo1** [comment]
> 请问是快递100还是快递100收件端的啊大佬

都是一样的

**Comment by a3946** [comment]
请问会写入广告的list么 写入的话我直接更新list了嘿嘿嘿

**Comment by eHpo1** [comment]
> 请问会写入广告的list么 写入的话我直接更新list了嘿嘿嘿

确认没副作用才会加进去

**Comment by a3946** [comment]
好的 麻烦了我先去试下

**Comment by a3946** [comment]
> 感谢反馈，请测试
> 解析
> 
> ```
> appv6.55haitao.com
> ```
> 
> 重写
> 
> ```
> 
> # 快递100
> ^https?+:\/\/p\.kuaidi100\.com\/mobile\/mobileapi\.do url reject-200
> # 55海淘
> ^https?+:\/\/appv6\.55haitao\.com\/IflyAd\/getAd url reject-200
> ```

请问复写是写到URL Rewrite 还是header rewrite

**Comment by eHpo1** [comment]
> > 感谢反馈，请测试
> > 解析
> > 
> > ```
> > appv6.55haitao.com
> > ```
> > 
> > 重写
> > 
> > ```
> > 
> > # 快递100
> > ^https?+:\/\/p\.kuaidi100\.com\/mobile\/mobileapi\.do url reject-200
> > # 55海淘
> > ^https?+:\/\/appv6\.55haitao\.com\/IflyAd\/getAd url reject-200
> > ```
> 
> 请问复写是写到URL Rewrite 还是header rewrite


[rewrite_local]

**Comment by a3946** [comment]
大佬 surge也有rewrite local的嘛

**Comment by a3946** [comment]
坐等大佬给surge的哈哈哈  另外添加mitm以后需要重新生成证书安装么

**Comment by eHpo1** [comment]
感谢支持，已更新至tide.list
