### ISSUE TITLE
[Surge]希望把京东开屏广告的规则迁移到Main.conf

### ISSUE THREAD

**Issue by skatingman** [eHpo1/Rules#23]
由于Surge的原因，希望能把位于Tide.list 193行的规则迁移到Main.conf，方便使用者自行注释
`URL-REGEX,"^https?+:\/\/api\.m\.jd\.com\/client\.action\?functionId=start$"`

```
# 不生效或失效的检查一下配置有没有这两条复写，删除试试
# ^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=start - reject
# ^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=(start|queryMaterialAdverts) - reject
```

**Comment by eHpo1** [comment]
> 由于Surge的原因，希望能把位于Tide.list 193行的规则迁移到Main.conf，方便使用者自行注释
> `URL-REGEX,"^https?+:\/\/api\.m\.jd\.com\/client\.action\?functionId=start$"`
> 
> ```
> # 不生效或失效的检查一下配置有没有这两条复写，删除试试
> # ^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=start - reject
> # ^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=(start|queryMaterialAdverts) - reject
> ```

这个不会的。这个规则以去广告为主。

**Comment by skatingman** [comment]
已解决：
在rule-set之前新增一行即可：
`URL-REGEX,"^https?+:\/\/api\.m\.jd\.com\/client\.action\?functionId=start$",DIRECT`
