### ISSUE TITLE
希望加上ZAKER的分流

### ISSUE THREAD

**Issue by Xwg999** [eHpo1/Rules#24]
使用现在的国内分流，zaker的页面加载很慢，有的文章加载不出来

**Comment by eHpo1** [comment]
感谢反馈，我这边检测https://www.myzaker.com/直连正常，是否考虑过网络问题

**Comment by Xwg999** [comment]
![image](https://user-images.githubusercontent.com/56066360/79142274-d3a8d600-7ded-11ea-9807-ec704cd2130e.png)
![image](https://user-images.githubusercontent.com/56066360/79142300-ddcad480-7ded-11ea-9cd2-941a3359987f.png)

**Comment by Xwg999** [comment]
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
加了一条分流订阅已解决

**Comment by eHpo1** [comment]
突然发现其实是DOMAIN-SUFFIX myzaker.com有这条分流的
