### ISSUE TITLE
clashx 导入 main.yaml 报错 Proxy 0: Missing type

### ISSUE THREAD

**Issue by whyour** [eHpo1/Rules#32]
Remote Config Format Error: Proxy 0: Missing type

**Comment by whyour** [comment]
你那个`type: 000`是不是可以换下 @eHpo1

**Comment by eHpo1** [comment]
> 你那个`type: 000`是不是可以换下 @eHpo1 

这个是示范，需要自己填的。

**Comment by whyour** [comment]
> > 你那个`type: 000`是不是可以换下 @eHpo1
> 
> 这个是示范，需要自己填的。

是的，但是我是更新的话，还要自己拷贝，而不能用远程链接去更新，我觉得这块写个clashx支持的类型，让远程下载不报错就ok

**Comment by whyour** [comment]
也ok，我不依赖这个软件了，我还是用wget下载吧。
