### ISSUE TITLE
更新 Telegram IP-CIDR

### ISSUE THREAD

**Issue by hly0928** [eHpo1/Rules#34]
参见 https://core.telegram.org/resources/cidr.txt

另外，目前 Quantumult X 商店版还不支持 IP-CIDR6 规则。

**Comment by hly0928** [comment]
> 另外，目前 Quantumult X 商店版还不支持 IP-CIDR6 规则。

最新商店版已支持。

**Comment by eHpo1** [comment]
感谢支持，已更新
