### ISSUE TITLE
shadowrocket去广告配置链接

### ISSUE THREAD

**Issue by e141313** [eHpo1/Rules#4]
小火箭的配置链接怎么不能用？

**Comment by e141313** [comment]
![Uploading C3031AD4-5679-4243-8D59-886EB05D7920.jpeg…]()

**Comment by e141313** [comment]
![303BAD7F-BC59-44B4-9A5D-301B0E3CFA8C](https://user-images.githubusercontent.com/61483784/77164272-debc5f00-6aea-11ea-8376-a22a02e9623d.jpeg)

**Comment by e141313** [comment]
没有规则？

**Comment by eHpo1** [comment]
> 没有规则？


https://raw.githubusercontent.com/eHpo1/Rules/master/Shadowrocket/Main.conf

我这边测试是正常的，有规则

**Comment by eHpo1** [comment]
> 没有规则？

不好意思，刚发现是readme写错了，永我刚才得链接

**Comment by eHpo1** [comment]
> 没有规则？

已更正，感谢提醒

**Comment by e141313** [comment]
小火箭规则已经更新了，无法正常打开网页。

**Comment by eHpo1** [comment]
> 小火箭规则已经更新了，无法正常打开网页。

抱歉，已经修复，更新试试

**Comment by e141313** [comment]
> > 没有规则？
> 
> https://raw.githubusercontent.com/eHpo1/Rules/master/Shadowrocket/Main.conf
> 
> 我这边测试是正常的，有规则

已经下载小火箭配置，但是使用上，网络有异常，网速慢。

**Comment by e141313** [comment]
网络问题已经解决了，不知道可以去除youtube app的广告吗

**Comment by eHpo1** [comment]
> 网络问题已经解决了，不知道可以去除youtube app的广告吗 

刚才在大佬的规则那回复你了，都是那个道理。

**Comment by e141313** [comment]
好的，谢谢。😂
