### ISSUE TITLE
飞书 > 工作台图标无法加载

### ISSUE THREAD

**Issue by hly0928** [eHpo1/Rules#40]
飞书 > 工作台图标不能正常载入，查看最近请求应该是命中了 `Liby.list` 中以下规则：

```
DOMAIN,sf3-ttcdn-tos.pstatp.com
DOMAIN,sf6-ttcdn-tos.pstatp.com
```

建议移除以上规则。

**Comment by eHpo1** [comment]
感谢支持，已更新。

**Comment by hly0928** [comment]
目前仍建议移除这两条，观察到还会导致网页版飞书的头像无法正常显示。

**Comment by eHpo1** [comment]
> 目前仍建议移除这两条，观察到还会导致网页版飞书的头像无法正常显示。

抱歉，这两条是不小心加上去的。上次文件被弄乱了。

**Comment by tanglueyi** [comment]
抱歉，被我瞎弄乱了
