### ISSUE TITLE
youtube的广告似乎无法去除

### ISSUE THREAD

**Issue by buxihuanqimingzi** [eHpo1/Rules#41]
这是我目前用过的最好的小火箭去广告规则了
但youtube的广告似乎无法去除，不知道是我使用有误还是目前确实无法去除呢

**Comment by eHpo1** [comment]
> 这是我目前用过的最好的小火箭去广告规则了
> 
> 但youtube的广告似乎无法去除，不知道是我使用有误还是目前确实无法去除呢

加了
```
*.googlevideo.com
```
这条https解密没。

**Comment by buxihuanqimingzi** [comment]
好的，按你说的，解决了，谢谢大神！
感谢你写的这个规则！
