### ISSUE TITLE
surge中引用Tide.list是否可以使用REJECT-TINYGIF规则

### ISSUE THREAD

**Issue by vhvg** [eHpo1/Rules#42]
在您维护的https://raw.githubusercontent.com/eHpo1/Rules/master/Surge4/Ruleset/Tide.list中包含
`URL-REGEX,"^https?+:\/\/api\.m\.jd\.com\/client\.action\?functionId=start$"`
这样一条规则，对此ruleset使用REJECT规则，将会使得京东历史价格script失效，经测试，若使用REJECT-TINYGIF规则，则不会影响京东历史价格script。

在有限的几个常用应用测试中，没有观察到REJECT-TINYGIF对该ruleset的去广告效果有影响，然而所测试的应用不多，因此无法确定REJECT-TINYGIF是否对于其他的URL-REGEX规则同样有效。

由于我不是程序员，不清楚REJECT与REJECT-TINYGIF在实现原理上是否有区别，请问从理论上讲，针对Tide.list使用REJECT-TINYGIF是否恰当？

若恰当，或许可以作为京东App去开屏广告与历史价格script共存的一个方法。

类似问题的讨论：https://github.com/yichahucha/surge/issues/56

**Comment by hly0928** [comment]
从原理上来说，`REJECT` 会对请求返回 `HTTP 404`（个人猜测，没有找到相关文档），`REJECT-TINYGIF` 会对请求返回 `HTTP 200` 和一个 1px 透明 GIF 图片（参见 [Surge iOS 3.0 Release Note](https://nssurge.zendesk.com/hc/zh-cn/articles/360000171474-Surge-iOS-3-0-Release-Note)）。

据我所知，`REJECT-TINYGIF` 一般用于解决一些 app 在使用普通 `REJECT` 后仍然持续进行大量请求，大部分情况下选择 `REJECT-TINYGIF` 不会出现问题。况且完全可以自定义 `Liby.list` 和 `Tide.list` 走 `Adblock` 之类的策略组，自行选择切换 `REJECT` 或是 `REJECT-TINYGIF`。

另外，Quantumult X 的 Rewrite 功能提供了多种 Reject 方式（参见官方 [示例配置](https://github.com/crossutility/Quantumult-X/blob/master/sample.conf#L139)），你可以使用 QX 进行相关测试。

**Comment by vhvg** [comment]
> 从原理上来说，`REJECT` 会直接打断命中的请求，`REJECT-TINYGIF` 会对请求返回 `HTTP 200` 和一个 1px 透明 GIF 图片（参见 [Surge iOS 3.0 Release Note](https://nssurge.zendesk.com/hc/zh-cn/articles/360000171474-Surge-iOS-3-0-Release-Note)）。
> 
> 据我所知，`REJECT-TINYGIF` 一般用于解决一些 app 在使用普通 `REJECT` 后仍然持续进行大量请求，大部分情况下选择 `REJECT-TINYGIF` 不会出现问题。况且完全可以自定义 `Liby.list` 和 `Tide.list` 走 `Adblock` 之类的策略组，自行选择切换 `REJECT` 或是 `REJECT-TINYGIF`。
> 
> 另外，Quantumult X 的 Rewrite 功能提供了多种 Reject 方式（参见官方 [示例配置](https://github.com/crossutility/Quantumult-X/blob/master/sample.conf#L139)），你可以使用 QX 进行相关测试。

感谢您的回复，现在已经使用了策略组，在REJECT-TINYGIF和REJECT中手动选择。昨晚之后又测试了一些应用，REJECT-TINYGIF目前均无问题，之后会继续观察，目前我将它作为京东App去开屏广告与历史价格script共存的方法。
