### ISSUE TITLE
b站港澳台能独立分流吗？

### ISSUE THREAD

**Issue by lowking** [eHpo1/Rules#45]
我用sub下面对bilibili.txt无法独立分流呢
要么全站都代理，要么都没走代理

**Comment by lowking** [comment]
我用的QuantumultX

**Comment by eHpo1** [comment]
> 我用sub下面对bilibili.txt无法独立分流呢
> 
> 要么全站都代理，要么都没走代理

全部代理后应该能看港澳台限定了吧。

**Comment by lowking** [comment]
> > 我用sub下面对bilibili.txt无法独立分流呢
> > 要么全站都代理，要么都没走代理
> 
> 全部代理后应该能看港澳台限定了吧。

那肯定的，但是所有视频都走代理了，有没办法就港澳台的走代理
还有一点就是你开启quanx，b站直连，这时候是无法看港澳台的，然后quanx分流策略那边选到代理，再切回b站，仍然无法观看。这个感觉是app的问题

现在我只能每次看港澳台都开关下，很蛋疼

**Comment by eHpo1** [comment]
> > > 我用sub下面对bilibili.txt无法独立分流呢
> 
> > > 要么全站都代理，要么都没走代理
> 
> > 
> 
> > 全部代理后应该能看港澳台限定了吧。
> 
> 
> 
> 那肯定的，但是所有视频都走代理了，有没办法就港澳台的走代理
> 
> 还有一点就是你开启quanx，b站直连，这时候是无法看港澳台的，然后quanx分流策略那边选到代理，再切回b站，仍然无法观看。这个感觉是app的问题
> 
> 
> 
> 现在我只能每次看港澳台都开关下，很蛋疼

是没办法达到你想要的效果，只能是全部走代理。直接选代理不重启app无效，我估计是因为启动app时有检测你是哪里的ip。
