### ISSUE TITLE
关于去除youtube广告

### ISSUE THREAD

**Issue by e141313** [eHpo1/Rules#5]
YouTube去广告会导致会员无法正常观看，规则默认没有开启YouTube的去广告，需要自行加上https解析
*.googlevideo.com
------------------------------------------
这个我放到https解密里面，还是有广告。😂
期待更好的方法，或者减少广告出现的频率。谢谢。

**Comment by eHpo1** [comment]
> YouTube去广告会导致会员无法正常观看，规则默认没有开启YouTube的去广告，需要自行加上https解析
> *.googlevideo.com
> ------------------------------------------
> 这个我放到https解密里面，还是有广告。😂
> 期待更好的方法，或者减少广告出现的频率。谢谢。

目前没有办法去掉更多广告，建议开会员
