### ISSUE TITLE
quanx 删除 region规则后，大量国内规则没法匹配上

### ISSUE THREAD

**Issue by wxdjs** [eHpo1/Rules#50]
quanx 删除 region规则后，大量国内ip规则没法匹配上，

**Comment by eHpo1** [comment]
在本地规则最后加上这一段就行了。
```
GEOIP,CN,DIRECT
```

**Comment by wxdjs** [comment]
目前是这么添加的，但是为啥删除，这个需要用户自己添加了

**Comment by eHpo1** [comment]
> 目前是这么添加的，但是为啥删除，这个需要用户自己添加了

出于一些回国用户考虑，还有lan目前看来用处不大，精简一下。

**Comment by wxdjs** [comment]
感谢回复，

**Comment by sghsd** [comment]
quanx 导入的conf39行报错，geoip, cn, direct 加到remote 里了

**Comment by eHpo1** [comment]
> quanx 导入的conf39行报错，geoip, cn, direct 加到remote 里了

已修正
