### ISSUE TITLE
Apple_API少了个回车

### ISSUE THREAD

**Issue by sengoku-f** [eHpo1/Rules#6]
https://github.com/eHpo1/Rules/blob/b5cf0e050079149539993ff92121417cfcfed9c2/Surge4/Ruleset/Apple_API.list#L16

**Comment by sengoku-f** [comment]
奇怪在 vscode 里面是两行的,在 github 里面就变成一行了

**Comment by eHpo1** [comment]
> 奇怪在 vscode 里面是两行的,在 github 里面就变成一行了

api里没问题，我倒是发现sub里有问题，

**Comment by sengoku-f** [comment]
> > 奇怪在vscode里面是两行的，在github里面就变成一行了
> 
> api里没问题，我倒是发现sub里有问题，

我这里会转换会出错
![image](https://user-images.githubusercontent.com/31064651/77717599-da78d000-701b-11ea-81de-9f8b58207d3f.png)

**Comment by eHpo1** [comment]
> > > 奇怪在vscode里面是两行的，在github里面就变成一行了
> 
> > 
> 
> > api里没问题，我倒是发现sub里有问题，
> 
> 
> 
> 我这里会转换会出错
> 
> ![image](https://user-images.githubusercontent.com/31064651/77717599-da78d000-701b-11ea-81de-9f8b58207d3f.png)
> 
> 

是有这个问题，我夜不太记得清是怎么产生的了，下次更新修复。

**Comment by eHpo1** [comment]
> > > 奇怪在vscode里面是两行的，在github里面就变成一行了
> 
> > 
> 
> > api里没问题，我倒是发现sub里有问题，
> 
> 
> 
> 我这里会转换会出错
> 
> ![image](https://user-images.githubusercontent.com/31064651/77717599-da78d000-701b-11ea-81de-9f8b58207d3f.png)
> 
> 

现在应该已经修正好了

**Comment by sengoku-f** [comment]
> > > > 奇怪在vscode里面是两行的，在github里面就变成一行了
> > 
> > 
> > > 
> > 
> > 
> > > api里没问题，我倒是发现sub里有问题，
> > 
> > 
> > 我这里会转换会出错
> > ![图片](https://user-images.githubusercontent.com/31064651/77717599-da78d000-701b-11ea-81de-9f8b58207d3f.png)
> 
> 现在应该已经修正好了

嗯嗯,不报错了
